name: Build and Push containers to GHCR (PROTO)

#This only runs if changes to decret itself or this workflow are made
on:
  push:
    branches:
    paths:
      - decret/proto.py
      - decret/Dockerfile.template
      - .github/workflows/build-and-push-proto.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - cve: cve-2016-3714
            options: "--directory imagetragick" 
          - cve: cve-2014-0160
            options: "--directory heartbleed"
          - cve: cve-2020-7247
            options: "--directory opensmtpd"
          - cve: cve-2023-22809
            options: "--directory sudoedit"
          - cve: cve-2022-1664
            options: "--directory dpkg"

    permissions:
      contents: read
      packages: write  # Needed to push to GHCR

    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: BUILD Docker Images
        run: |
          CVE_NAME="${{ matrix.cve }}"
          STRIPPED_CVE="${CVE_NAME#cve-}"
          #Build, tag and push in order
          python3 -m decret.proto -n "$STRIPPED_CVE" ${{ matrix.options }} 

      - name: TAG Docker Images
        run: docker tag "${{ matrix.cve }}" "ghcr.io/pi3dra/decret/${{ matrix.cve }}-proto:latest"

      - name: PUSH Docker Images
        run: docker push "ghcr.io/pi3dra/decret/${{ matrix.cve }}-proto:latest"



          

