name: Python CI (Pylint + Pytest)

#empty to run on dev and feature branches
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with pylint (fail only on errors)
      #Prototyping, I don't want the CI to fail on similar code to decret.py
      run: |
        pylint decret/proto.py decret/utils.py

    - name: Run tests with pytest
      run: |
        pytest

